In [1]:
import numpy as np

In [2]:
# create an array
a = [1,2,3,4,5]
a_array = np.array(a)
a_array

array([1, 2, 3, 4, 5])

In [3]:
# Again create another array
b = ("mango", "papaya", "litchi", "apple")
array_b = np.array(b)
array_b

array(['mango', 'papaya', 'litchi', 'apple'], dtype='<U6')

In [4]:
# Again create another array
b = (200.23,20.25,15.00,45.05)
array_b = np.array(b)
array_b

array([200.23,  20.25,  15.  ,  45.05])

In [5]:
array_b.dtype # check the data types

dtype('float64')

In [7]:
# check the dimension 
array_b.ndim

1

In [11]:
a = [[2,3,4], [3,4,5]]
array_a1 = np.array(a)
array_a1.ndim

2

In [13]:
a = [[2,3,4], [3,4,5]]
array_a1 = np.array(a)
array_a1.dtype

dtype('int32')

In [15]:
array_a1

array([[2, 3, 4],
       [3, 4, 5]])

In [16]:
# check the shape
array_a1.shape

(2, 3)

In [17]:
array_b.size

4

In [21]:
# access elements in array
array_a1[0,1]

np.int32(3)

In [22]:
array_a1[1,2]

np.int32(5)

In [33]:
#check  the array again

a = [[1,2,3,4],[2,3,4,5],[4,5,6,7]]
array_b1 = np.array(a)

In [34]:
array_b1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [35]:
#check the elements in arrays
array_b1[2,2]

np.int32(6)

In [36]:
array_b1.ndim

2

In [37]:
#check the negative elements in array[r,c]

array_b1[0,-2]

np.int32(3)

In [38]:
#check the negative elements in array[r,c]

array_b1[1,-2]

np.int32(4)

In [40]:
# we use also slicing  here in arrays
array_b1[1,:]

array([2, 3, 4, 5])

In [41]:
array_b1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [42]:
array_b1[2,:]

array([4, 5, 6, 7])

In [43]:
# Assign the values / change the values

array_b1[2,2]= 21

In [44]:
array_b1 # Now the values has changed.

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 4,  5, 21,  7]])

In [48]:
# Now 3D arrays
c = [[[1,2],[2,6]],[[2,3],[2,6]]]
array_c1 = np.array(c)
array_c1.shape

(2, 2, 2)

In [49]:
c = [[[1,2],[2,6]],[[2,3],[2,6]]]
array_c1 = np.array(c)
array_c1

array([[[1, 2],
        [2, 6]],

       [[2, 3],
        [2, 6]]])

In [50]:
array_c1.ndim

3

In [51]:
# so now check the elements in arrays 
array_c1[0,0,0]

np.int32(1)

In [52]:
# so now check the elements in arrays 
array_c1[1,1,0]

np.int32(2)